DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE movies (
  id SERIAL PRIMARY KEY NOT NULL,
  rating INTEGER NOT NULL DEFAULT 0,
  title VARCHAR(255) NOT NULL,
  genre VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL
);

ALTER SEQUENCE movies_id_seq RESTART WITH 1000 INCREMENT BY 1;

CREATE TABLE products (
  id SERIAL PRIMARY KEY NOT NULL,
  rating INTEGER NOT NULL DEFAULT 0,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL DEFAULT 0,
  url VARCHAR(255) NOT NULL
);

ALTER SEQUENCE products_id_seq RESTART WITH 3000 INCREMENT BY 1;
